# Inventario para laboratorio AU294
# Red Hat Enterprise Linux Automation with Ansible

[control]
ansible-control ansible_host=10.10.10.10 ansible_connection=local

[managed]
managed-node-01 ansible_host=10.10.10.11
managed-node-02 ansible_host=10.10.10.12
managed-node-03 ansible_host=10.10.10.13

[webservers]
managed-node-01
managed-node-02

[dbservers]
managed-node-03

[lb]
managed-node-03

[app]
managed-node-01
managed-node-02
managed-node-03

[lab:children]
control
managed
